### ISSUE TITLE
Windows rendering issue: bold 'e' characters

### ISSUE THREAD

**Issue by davidfurlong** [jpt/barlow#55]
It appears that the bold version 'e' characters are being rendered incorrectly only on windows. Self hosted woff2. Tried updating to newest version and that didn't resolve it
![image (4)](https://user-images.githubusercontent.com/614768/64267292-71722380-cf36-11e9-8e61-7d42708372e9.png)
![image (3)](https://user-images.githubusercontent.com/614768/64267294-71722380-cf36-11e9-9681-21f7458ca122.png)

**Comment by jpt** [comment]
Hi @davidfurlong - thanks for opening the issue, I'll look into it. In which browser and version of Windows is this happening?

**Comment by davidfurlong** [comment]
Chrome & windows 10

**Comment by jpt** [comment]
Hi @davidfurlong  -- thanks for the additional information, I'm looking into it. I wonder if this fix works as a temporary solution? https://coderwall.com/p/9tecwq/fix-poor-font-rendering-in-chrome-on-windows

**Comment by davidfurlong** [comment]
Thanks for looking into it

**Comment by jpt** [comment]
Hi @davidfurlong -- it looks like there was an error with the "virtual masters" for the letter "e" in the source file that I think caused some bad autohinting-related metadata. I've fixed the source and generated new WOFF2 binaries -- can you let me know if the attached files fix your problem? [Click to download -- woff2.zip](https://github.com/jpt/barlow/files/3585787/woff2.zip)

If this works I'll go ahead and push out a new version of Barlow. Thanks again for opening the issue.

**Comment by davidfurlong** [comment]
hey @jpt I appreciate you looking into this and finding a possible resolution. I'll be honest, we decided to switch out barlow for another font due to this issue and I don't have access directly to a windows environment -- therefore its prohibitively time consuming for me to now try to see if the above font download fixed the issue. I hope you can find another reproduction environment and I'm sorry to drop this on you

**Comment by jpt** [comment]
@davidfurlong -- no worries at all, I appreciate bug report! I'll spin up a VM to give it a proper evaluation.

**Comment by briandipert** [comment]
I'm having similar issues but it is also effecting the capital "E". This is occurring in IE11, Firefox and Chrome on Windows. I tried your new WOFF2 binaries and the issue is still occurring.

![image](https://user-images.githubusercontent.com/55999485/65907114-b8b2cf00-e391-11e9-938d-440c2c72b545.png)

**Comment by jpt** [comment]
Thanks @briandipert -- can you give these a try? Also, can you let me know if WOFF (not WOFF2) files have the same problem? 

[Barlow-New-WOFF2.zip](https://github.com/jpt/barlow/files/3674790/Barlow-New-WOFF2.zip)

**Comment by briandipert** [comment]
These WOFF2 files fixed the issues for me!

On the WOFF files, the Barlow Regular font does not appear to have the issue but the Barlow Condensed Regular font does it (see image below)
![image](https://user-images.githubusercontent.com/55999485/66149856-f6a63200-e5e1-11e9-9342-1541f7981550.png)

**Comment by jpt** [comment]
@briandipert thanks so much for the report, you've helped me identify the problem: the latest version of Barlow's WOFF and WOFF2 files are using OpenType outlines instead of TrueType outlines, so ttfAutoHint is not being applied / Windows compatibility has suffered. I'll get a new version up shortly. Thanks again for the help!

**Comment by Sopamo** [comment]
We have the same issue with the WOFF and WOFF2 files and can replicate it on OSX and Linux (in Chrome):

![image](https://user-images.githubusercontent.com/1202596/66815570-cabb7280-ef38-11e9-91fa-61ff2f28c170.png)

For us this also only happens with the bold style.

**Comment by naeon** [comment]
@jpt Could you give an estimate on when this issue might be fixed? Thank you!

**Comment by briandipert** [comment]
@jpt do you have a TTF file of the latest version of Barlow?

**Comment by jpt** [comment]
I'm re-hinting the font in the next week or so. will update then.

**Comment by jpt** [comment]
Hinting has been updated in the source, I will generate new TTF binaries soon: https://github.com/jpt/barlow/tree/1.5

**Comment by jpt** [comment]
new TTF files can be found here: https://github.com/jpt/barlow/tree/1.5/fonts/ttf
I will merge them into the main branch once I've finished testing

**Comment by agusmba** [comment]
I've tried to test the TTF files on http://www.cyreal.org/Font-Testing-Page/ (drag-n-drop) but they are not loading correctly. The OTF versions seem to load ok. I don't know if its Cyreal's page fault, or something in the TTF is strange. Previous Barlow TTF versions load correctly in that page.
Windows preview seems to show the new TTF files ok also.

Another testing page: http://webfont-test.com/ is also not working on the new TTFs.

**Comment by jpt** [comment]
Looking into the TTFs, thanks for letting me know

**Comment by jpt** [comment]
Hi @agusmba — can you give the latest TTF files here a try? I think it will fix the issue. Thanks all in this thread for reporting [Barlow1.5-RC1.zip](https://github.com/jpt/barlow/files/7655026/Barlow1.5-RC1.zip)

**Comment by agusmba** [comment]
> Hi @agusmba — can you give the latest TTF files here a try? I think it will fix the issue. Thanks all in this thread for reporting [Barlow1.5-RC1.zip](https://github.com/jpt/barlow/files/7655026/Barlow1.5-RC1.zip)

Will do. I'll edit this comment with my results. Thanks!

**UPDATE**
The new TTF files load correctly. 👍
However doing a quick comparison with version 1.422, I see some strange artifacts:

![image](https://user-images.githubusercontent.com/3104020/145392847-5888cb02-1d1b-4ebb-9e9d-0518cc3277b0.png)
Notice the uneven characters at size 18 compared with v1.422

Using the testing page I used before, there seem to be some antialiasing not working properly:
![image](https://user-images.githubusercontent.com/3104020/145393369-3fd015a0-7085-474f-96f8-47537ac794f2.png)

compared to version 1.422 which looks better regarding aliasing (sorry if this is not the right term):
![image](https://user-images.githubusercontent.com/3104020/145393454-9c1bd50a-9229-49c7-914f-034c29df53ce.png)

**Comment by agusmba** [comment]
The OTF is a bit better than the TTF, but still has some quirks:
![image](https://user-images.githubusercontent.com/3104020/145395037-8c68d6fa-e3f5-4db0-90a5-db0d5f8ed471.png)
