### ISSUE TITLE
Middle dot problem with double el (Barlow Google Fonts)

### ISSUE THREAD

**Issue by Guuustav** [jpt/barlow#91]
Hi Jeremy,

Good morning. I hope you're well. I have found that the middle dot does not work correctly with the double letter el. In my native language, Catalan (language of a region of Spain), it is common to find words with the middle dot. The Barlow is mischievous and when you write the second letter she places the dot on top of the first one Haha.

This error is with the version of Google Fonts which is the one I use since I also need the letter Ñ that I couldn't use with the Github version.

Arial and Barlow comparison:
<img width="1118" alt="Captura de Pantalla 2023-07-18 a las 8 43 38" src="https://github.com/jpt/barlow/assets/99183395/19efe84a-f801-442d-9a06-fe254846616f">

Middle dot in Wikipedia:
https://en.m.wikipedia.org/wiki/Interpunct#Catalan

Have a good day.

**Comment by Guuustav** [comment]
I've done some testing and it seems like a bit of a random bug. I don't know how to help more because I don't know how to define when it happens because right now it only happens to me in a text box of a letter made up in InDesign. But if I create a new text box in that same document then it works correctly. In a new InDesign, Illustrator or Word document I don't have that problem. It's a mystery.

On the other hand, my coworker with the same Barlow from Google Fonts has this same problem in Word. It doesn't matter if he starts writing with the Calibri and changes it to Barlow, or writes directly with the Barlow. In both cases he has the problem that the middle point rises to the first letter el.

I have also tried changing the tracking of the paragraph and the kerning between the two els and the middle point without solving it. It does not happen with capital letters, nor between numbers or between another pair of letters.

I am attaching an InDesign document with the problem to see if you can figure something out.
[Middle dot.indd.zip](https://github.com/jpt/barlow/files/12077825/Middle.dot.indd.zip)

Let's see if there is luck and we find the solution. I am the chief designer of the city council of my city and we have established Barlow as the new corporate typeface and in Catalan, our official language, it is very common to find words with a middle dot. Until yesterday, laying out a letter from the mayoress of the city, we did not detect this problem. I got around it by writing a space after the middle dot and tightening the kerning to visually remove that space. Haha.

**Comment by jpt** [comment]
Hi @Guuustav thank you for raising this issue. It is fixed in the 1.5 version of Barlow which is not yet released. You can download it and see more about the issue [here](https://github.com/jpt/barlow/issues/64). I am hoping to publish the fix for general release soon, please let me know if you need any assistance

**Comment by Guuustav** [comment]
Thank you very much for your ofreciment. My apologies for duplicating the topic.

We will wait for the 1.5 update because I commented in the other [thread](https://github.com/jpt/barlow/issues/87) that we opened that we need the "ñ". For this reason we are using the TTF version of Google Fonts that we saw did not have the Ñ problem.

When you have the new version with the l·l and ñ corrected, will you update the version of Google Fonts?

Thanks in advance and great work Jeremy!

Kind Regards.

**Comment by Guuustav** [comment]
Hello @jpt I hope you are good. 

I just found that Glyphs provides the solution to the problem on its own website. I don't know if you already knew it:

https://glyphsapp.com/learn/localize-your-font-catalan-punt-volat

Have a good day.

**Comment by jpt** [comment]
Hi @Guuustav As you may remember from above, the punt volat is fixed in the 1.5 branch. If this has changed, I'll have to take another look. I don't know when I'll be able to prioritize it

**Comment by Guuustav** [comment]
My apologies. You're right. What we talked about [a few weeks ago](https://github.com/jpt/barlow/issues/87#issuecomment-1748599849) was about the letters Ñ/ñ being missing in version 1.5.

With all the tests I did a few weeks ago I was now confused. In the exhaustive tests I did in versions 1.422, 1.5 and Google Fonts, on L·L, l·l, Ñ and ñ. In 1.5 the letters Ñ/ñ are written as N/n.

I apologize again and have a good weekend.

I close this thread.

**Comment by xcolomer** [comment]
Hello Jeremy,
First, congratulations for the Barlow project. 

I've been testing the typeface Barlow as a web font (fonts/woff) on the font testing site [Cyreal.org](http://www.cyreal.org/).
The "punt volat" (middle dot) does not work correctly with the double letter el. Even though the repository Github says that it is corrected in version 1.5.

<img width="790" alt="Captura de Pantalla 2024-01-30 a les 12 39 33" src="https://github.com/jpt/barlow/assets/12183886/04ba3893-e88e-4479-803a-48475bc91eef">

In Google fonts, the "punt volat" (middle dot), only works well if you do it with "Shift+3".
This is the text I tested: cel·la, CEL·LA, CEĿLA, ceŀla

<img width="651" alt="Captura de Pantalla 2024-01-30 a les 13 16 54" src="https://github.com/jpt/barlow/assets/12183886/ef6bba09-1bde-4cc7-8532-5553d75092f3">

Let me know if there is any way to solve this error?
Thanks in advance

**Comment by xcolomer** [comment]
> Hi Jeremy,
> 
> Good morning. I hope you're well. I have found that the middle dot does not work correctly with the double letter el. In my native language, Catalan (language of a region of Spain), it is common to find words with the middle dot. The Barlow is mischievous and when you write the second letter she places the dot on top of the first one Haha.
> 
> This error is with the version of Google Fonts which is the one I use since I also need the letter Ñ that I couldn't use with the Github version.
> 
> Arial and Barlow comparison: <img alt="Captura de Pantalla 2023-07-18 a las 8 43 38" width="1118" src="https://private-user-images.githubusercontent.com/99183395/254169521-19efe84a-f801-442d-9a06-fe254846616f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTgxOTgsIm5iZiI6MTcwNjYxNzg5OCwicGF0aCI6Ii85OTE4MzM5NS8yNTQxNjk1MjEtMTllZmU4NGEtZjgwMS00NDJkLTlhMDYtZmUyNTQ4NDY2MTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDEyMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NzFkN2UxODE3ZjNjYjk1YWI1NWZiMDRkODdjYmIwZDNlNzY3NjI4YzUwODA2ZDM1MzYwNjM0Y2JiMzUzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CDf2zwai7XNbh-TQOdFinFoG8jizJPtIXFSfyPHcca0">
> 
> Middle dot in Wikipedia: https://en.m.wikipedia.org/wiki/Interpunct#Catalan
> 
> Have a good day.

@Guuustav Have you found any solution for this error?
Thanks

**Comment by Guuustav** [comment]
Hi @xcolomer 

As you found out, version 1.5 has the middle dot problem corrected. You can download it from here:

[https://github.com/jpt/barlow/tree/1.5/fonts](https://github.com/jpt/barlow/tree/1.5/fonts)

But this version 1.5 has another big problem in the Spanish language. The Ñ is not represented. Jeremy is already aware and indicated that it will be corrected in a future version. I myself opened this other thread to inform Jeremy:

[https://github.com/jpt/barlow/issues/87](https://github.com/jpt/barlow/issues/87)

All the best.

**Comment by zuruckzugehen** [comment]
Hi Jeremy! Another catalan developer here!
Thanks for your adjustments to include l·l character, but I have realized that it has a little flaw.
When <html lang="es"> (Spanish) the l·l is working properly, but when <html lang="ca">, that it is the ISO code for the Catalan language, the issue is still visible. So, this makes Barlow unusable for catalan pages.

<img width="1459" height="865" alt="Image" src="https://github.com/user-attachments/assets/da568b07-08ab-4c6c-a548-5f426e70207b" />
